### ISSUE TITLE
error output is confusing when multiple files are being processed

### ISSUE THREAD

**Issue by wez** [azzamsa/gelatyx#1]
It's unclear which file the error belongs to; could you explicitly put the filename in the context?
In addition, I think it would be helpful to also print the snippet that is being formatted, as there could be a number of similar snippets in any given file

```
docs/config/lua/wezterm/config_file.md is formatted
error parsing: error occurred while creating ast: unexpected token `{`. (starting from line 1, character 1 and ending on line 1, character 2)
additional information: leftover token
docs/config/lua/wezterm/default_wsl_domains.md is formatted
```

**Comment by azzamsa** [comment]
Hi.

Thank you for the report.

![image](https://user-images.githubusercontent.com/17734314/181442944-ebb5fd62-5478-4b85-89f6-ef78432472b1.png)

Is this readable enough or do you have more some suggestions?

**Comment by wez** [comment]
It looks good!

One suggestion is: could the line numbers be adjusted to match the offset into the .md file?  For example, if the bad lua code is at line 30 in the markdown file, then the "starting from line 1" would be more helpful if it were "starting from line 31".

Another is: If the underlying stylua api gives you enough error information, you might want to consider using something like https://github.com/brendanzab/codespan so that it can annotate the code spans with the relevant error(s)

**Comment by azzamsa** [comment]
> Another is: If the underlying stylua api gives you enough error information, you might want to consider using something like [brendanzab/codespan](https://github.com/brendanzab/codespan) so that it can annotate the code spans with the relevant error(s)

Hi, @wez.

I am so sorry for the long wait, but the feature is now complete.

- check

![image](https://user-images.githubusercontent.com/17734314/210688466-f1811d7c-1165-439b-b3dd-efb5266e0b35.png)

![image](https://user-images.githubusercontent.com/17734314/210688704-a69fe1f9-0428-44b6-a7d7-34044efaa0a6.png)

![image](https://user-images.githubusercontent.com/17734314/210689116-e487abf4-9496-4681-8408-79eba11e6a9d.png)


- format

![image](https://user-images.githubusercontent.com/17734314/210688912-39e6aa08-b54b-42b7-90ce-e125ee4d2ff6.png)

![image](https://user-images.githubusercontent.com/17734314/210689016-25e691fe-8024-4a38-bd47-245979fd9f86.png)


Would you like to compile the binary from master and check in your end?

**Comment by wez** [comment]
This looks great, many thanks!

**Comment by azzamsa** [comment]
> This looks great, many thanks!

Thank you, will cut the release in couple hours.
