### ISSUE TITLE
Ability to suppress per-file info unless the file was changed or has issues

### ISSUE THREAD

**Issue by wez** [azzamsa/gelatyx#6]
Hi!

I'm using gelatyx in a couple of projects now, and I'm feeling a little overwhelmed by the volume of the output.
I would love it if there was a quiet mode (perhaps it should be the default mode, and there should be a --verbose option?  I don't mind either way!) where lines like:

```
Unchanged docs/userguide/preface/index.md
```

and, for `--check`:

```
docs/userguide/preface/index.md is formatted
```

could be skipped; in those cases, the file was not changed, or would not be changed for the `--check` case.

**Comment by azzamsa** [comment]
Done. :)

Feel free to reopen if you find any issue

**Comment by wez** [comment]
Thanks!
